# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SchoolDiaryBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: SchoolDiaryBundle:User, property: email }

    firewalls:
        secured_area:
            # this firewall applies to all URLs
            pattern: ^/

            anonymous: true

            form_login:
                check_path: security_login

                login_path: security_login

                always_use_default_target_path: true

                csrf_token_generator: security.csrf.token_manager

            logout:
                target: homepage
                path: security_logout



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/create$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }


    role_hierarchy:
        ROLE_TEACHER: ROLE_USER
        ROLE_ADMIN: ROLE_TEACHER
