# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SchoolDiaryBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: SchoolDiaryBundle:User, property: email }

    firewalls:
        secured_area:
            # this firewall applies to all URLs
            pattern: ^/

            anonymous: true

            form_login:
                check_path: security_login

                login_path: security_login

                csrf_token_generator: security.csrf.token_manager

            logout:
                path: security_logout

                target: home
    access_control:
