<?php

namespace SchoolDiaryBundle\Repository;

/**
 * AbsencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsencesRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getCountByUser()
//    {
//        $query = $this->createQueryBuilder('a');
//        $query
//            ->innerJoin('a.student', 's')
//            ->select('')
//            ->where('s.studentClass = :identifier')
//            ->setParameter('identifier', $classId);
//
//        return $query->getQuery()->getResult();
//    }
}
