<?php

namespace SchoolDiaryBundle\Repository;

/**
 * DayRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
