<?php

namespace SchoolDiaryBundle\Repository;

/**
 * PersonalGradesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use SchoolDiaryBundle\helpers\ColumnHydrator;
class PersonalGradesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGradesForClass($classId)
    {
        $em = $this->getEntityManager();
        $em->getConfiguration()->addCustomHydrationMode('COLUMN_HYDRATOR', ColumnHydrator::class);

        $query = $this->createQueryBuilder('g');
        $query
            ->select('g.value')
            ->innerJoin('g.student', 's')
            ->where('s.studentClass = :identifier')
            ->setParameter('identifier', $classId);

        return $query->getQuery()->getResult('COLUMN_HYDRATOR');
    }

    public function getAllGradesValues()
    {
        $em = $this->getEntityManager();
        $em->getConfiguration()->addCustomHydrationMode('COLUMN_HYDRATOR', ColumnHydrator::class);

        $query = $this->createQueryBuilder('g');
        $query->select('g.value');

        return $query->getQuery()->getResult('COLUMN_HYDRATOR');
    }
}
