<?php

namespace SchoolDiaryBundle\Repository;

/**
 * PersonalGradesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalGradesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGradesForClass($classId)
    {
        $query = $this->createQueryBuilder('g');
        $query
            ->innerJoin('g.student', 's')
            ->where('s.studentClass = :identifier')
            ->setParameter('identifier', $classId);

        return $query->getQuery()->getResult();
    }
}
