<?php

namespace SchoolDiaryBundle\Repository;

/**
 * PersonalGradesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalGradesRepository extends \Doctrine\ORM\EntityRepository
{
}
